"""
StreamClip AI — Real Integration Test
Tests: Twitch API auth, streamer live-check, database ops, SEO generation
"""

import os
import sys
import time

# Force UTF-8 output on Windows
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

import config
from database import Database

print("=" * 60)
print("  StreamClip AI — Integration Test")
print("=" * 60)

# ── 1. Verify credentials loaded ────────────────────────────
print("\n[1] Checking credentials...")
print(f"  Twitch Client ID:     {'SET (' + config.TWITCH_CLIENT_ID[:8] + '...)' if config.TWITCH_CLIENT_ID else 'MISSING'}")
print(f"  Twitch Client Secret: {'SET (' + config.TWITCH_CLIENT_SECRET[:8] + '...)' if config.TWITCH_CLIENT_SECRET else 'MISSING'}")
yt_key = os.getenv("YOUTUBE_API_KEY", "")
yt_cid = os.getenv("YOUTUBE_CLIENT_ID", "")
yt_csec = os.getenv("YOUTUBE_CLIENT_SECRET", "")
print(f"  YouTube API Key:      {'SET (' + yt_key[:12] + '...)' if yt_key else 'MISSING'}")
print(f"  YouTube Client ID:    {'SET (' + yt_cid[:12] + '...)' if yt_cid else 'MISSING'}")
print(f"  YouTube Client Secret:{'SET (' + yt_csec[:12] + '...)' if yt_csec else 'MISSING'}")

# ── 2. Database operations ──────────────────────────────────
print("\n[2] Testing database...")
db = Database()
stats = db.get_stats()
print(f"  Database: OK")
print(f"  Current stats: {stats}")

# Add the 3 streamers to DB
streamers_to_add = [
    ("IShowSpeed", "twitch", "ishowspeed", "https://www.twitch.tv/ishowspeed"),
    ("Kai Cenat", "twitch", "kaicenat", "https://www.twitch.tv/kaicenat"),
    ("Adin Ross", "twitch", "adinross", "https://www.twitch.tv/adinross"),
]

for name, platform, channel, url in streamers_to_add:
    try:
        sid = db.add_streamer(name=name, platform=platform, channel=channel, url=url, enabled=True, auto_approve=False)
        print(f"  Added streamer: {name} (id={sid})")
    except Exception as e:
        if "UNIQUE" in str(e):
            print(f"  Streamer already exists: {name}")
        else:
            print(f"  Error adding {name}: {e}")

all_streamers = db.get_streamers()
print(f"  Total streamers in DB: {len(all_streamers)}")
for s in all_streamers:
    print(f"    - {s['name']} ({s['platform']}) {s['url']}")

# ── 3. Twitch API live-check ────────────────────────────────
print("\n[3] Testing Twitch API...")
if config.TWITCH_CLIENT_ID and config.TWITCH_CLIENT_SECRET:
    from watcher.monitor import StreamMonitor, TwitchAuth

    auth = TwitchAuth()
    try:
        token = auth.get_token()
        print(f"  Twitch OAuth token: OK (got token)")
    except Exception as e:
        print(f"  Twitch OAuth FAILED: {e}")
        token = None

    if token:
        import requests
        headers = {
            "Client-Id": config.TWITCH_CLIENT_ID,
            "Authorization": f"Bearer {token}",
        }

        for name, _, channel, _ in streamers_to_add:
            try:
                resp = requests.get(
                    f"{config.TWITCH_HELIX_URL}/streams",
                    params={"user_login": channel},
                    headers=headers,
                    timeout=10,
                )
                resp.raise_for_status()
                data = resp.json().get("data", [])
                if data:
                    stream = data[0]
                    print(f"  {name}: LIVE - \"{stream['title']}\" ({stream['viewer_count']} viewers)")
                else:
                    print(f"  {name}: OFFLINE")
            except Exception as e:
                print(f"  {name}: ERROR - {e}")
else:
    print("  SKIPPED - Twitch credentials not set")

# ── 4. SEO generation test ──────────────────────────────────
print("\n[4] Testing SEO generation...")
from processor.seo import SEOGenerator

seo = SEOGenerator()
result = seo.generate(
    transcript="Oh my God did you see that play? He just hit a crazy no-scope headshot! Chat is going wild right now, this is insane! Let's go!",
    streamer_name="IShowSpeed",
    emotion="joy",
    platform="twitch",
)

print(f"  Title: {result.title}")
print(f"  Description: {result.description[:100]}...")
print(f"  Tags: {result.tags[:5]}")
print(f"  Hook text: {result.hook_text}")
print(f"  Generated by: {result.generated_by}")

# ── 5. Verify FFmpeg ────────────────────────────────────────
print("\n[5] Checking system dependencies...")
import shutil
for dep in ["ffmpeg", "ffprobe", "streamlink", "ollama"]:
    path = shutil.which(dep)
    print(f"  {dep}: {'OK (' + path + ')' if path else 'NOT FOUND'}")

# ── 6. Save a test clip record to DB ────────────────────────
print("\n[6] Creating test clip record in database...")
clip_id = f"test_clip_{int(time.time())}"
db.save_clip(
    clip_id=clip_id,
    streamer_name="IShowSpeed",
    platform="twitch",
    clip_path=str(config.CLIPS_DIR / f"{clip_id}.mp4"),
    duration=45,
    moment_score=0.82,
    emotion="joy",
    transcript="Oh my God did you see that play...",
)
print(f"  Created clip: {clip_id}")

clips = db.get_clips(limit=5)
print(f"  Total clips in DB: {len(clips)}")
for c in clips:
    print(f"    - [{c['status']}] {c['title'][:50]}...")

# ── Done ────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  Integration test complete!")
final_stats = db.get_stats()
print(f"  Final DB stats: {final_stats}")
print("=" * 60)

db.close()
